[package]
name = "vss-sample-rust"
version = "0.1.0"
authors = ["johnathan <johnathanfercher22@gmail.com>"]

[dependencies]
vss-core = { git = "https://github.com/VSS-SDK/VSS-CoreRust", branch = "master" }